#!/usr/bin/env ruby

require './tunnel'
require 'yaml'

opts = YAML.load_file('./config.yml')
tunnel = Tunnel.new(opts)

trap("INT") { tunnel.stop; exit }

begin
  tunnel.start
rescue => e
  puts "ERROR"
  puts e

  tunnel.stop
end
